name: Feature Test
on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches-ignore:
      - '!feature/**'

jobs:
  check_pr:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - id: check
        run: |
          if [[ "${{ github.event_name }}" == "push" ]] || [[ "${{ github.event.pull_request.base.ref }}" == feature/* ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

  feature-test:
    needs: check_pr
    if: needs.check_pr.outputs.should_run == 'true'
    uses: nimba-actions/standard-workflows/.github/workflows/feature-unlocked.yml@main
    secrets:
      dev-hub-auth-url: ${{ secrets.DEV_HUB_AUTH_URL }}
    with:
      cumulusci-version: "3.80.0"
      sfdx-version: "7.209.6"
