name: Test Feature (Unlocked)

on:
  pull_request:
    branches:
      - feature/**

jobs:
  feature-test:
    if: startsWith(github.head_ref, 'feature/')
    uses: nimba-actions/standard-workflows/.github/workflows/feature-unlocked.yml@main
    secrets:
      dev-hub-auth-url: ${{ secrets.DEV_HUB_AUTH_URL }}
    with:
      cumulusci-version: "3.80.0"
      sfdx-version: "7.209.6"