name: Install Beta

on:
  workflow_call:
    inputs:
      dev-org-auth-url:
        required: true
        type: string
      org-name:
        required: true
        type: string
        default: beta
      cumulusci-version:
        required: false
        type: string
      flow-name:
        required: true
        type: string

jobs:
    install-beta:
        uses: nimba-actions/standard-workflows/.github/workflows/install-beta.yml@main
        secrets:
            beta-org-auth-url: ${{ inputs.dev-org-auth-url }}
        with:
            cumulusci-version: ${{ inputs.cumulusci-version }}