name: Release Production (Unlocked)

on:
  workflow_dispatch:
    inputs:
      cumulusci-version:
        required: false
        type: string

jobs:
  upload-prod:
    uses: nimba-actions/standard-workflows/.github/workflows/production-unlocked.yml@main
    secrets:
      dev-hub-auth-url: ${{ secrets.DEV_HUB_AUTH_URL }}
    with:
      cumulusci-version: "3.78.0"
      org-name: "prod"